data_dir: /work/snagabhushan_umass_edu/dataset/nlq_official_v1/
save_dir: dataset
video_f_path: official
num_querys: 5
suffix: None
max_pos_len: 1000
video_seq_len: 1

## text features
query_fmodel: roberta-large

## dataloader
batch_size: 16

## train 
epochs: 300
mode: train


## model 
save_model_dir: save
model_name: join_2_layers
model_version: 2
enc_layers: 2
dec_layers: 2
hidden_dim: 1024
dropout: 0.1
nheads: 8
dim_feedforward: 1024
pre_norm: True
input_dropout: 0.5
n_input_proj: 2


## loss 
set_cost_span: 1
set_cost_giou: 3
set_cost_query: 2
aux_loss: True
pred_label: cos

## train
lr: 0.0001
wd: 0.0001
lr_drop_step: 50